### ISSUE TITLE
.vue files with import statements don't get transformed correctly

### ISSUE THREAD

**Issue by sunyatasattva** [znck/vue-plugin#3]
If I run `npm run build` on the example template (nothing changed), I get this error:

```
Error transforming vue-plugin/src/components/Hello.vue with 'vue' plugin: 'import' and 'export' may appear only with 'sourceType: module' (7:0)
SyntaxError: Error transforming vue-plugin/src/components/Hello.vue with 'vue' plugin: 'import' and 'export' may appear only with 'sourceType: module' (7:0)
3 : 
4 : 
5 : 
6 : 
7 : import upper from 'lodash/startCase';
    ^
    at Parser.pp$4.raise (vue-plugin/node_modules/vue-template-es2015-compiler/buble.js:2231:15)
    at Parser.pp$1.parseStatement (vue-plugin/node_modules/vue-template-es2015-compiler/buble.js:727:16)
    at Parser.pp$1.parseTopLevel (vue-plugin/node_modules/vue-template-es2015-compiler/buble.js:648:25)
    at Parser.parse vue-plugin/node_modules/vue-template-es2015-compiler/buble.js:526:17)
    at parse (vue-plugin/node_modules/vue-template-es2015-compiler/buble.js:3108:39)
    at Object.transform (vue-plugin/node_modules/vue-template-es2015-compiler/buble.js:11969:9)
    at transpile (vue-plugin/node_modules/vue-template-es2015-compiler/index.js:17:20)
    at injectRender (vue-plugin/node_modules/rollup-plugin-vue/dist/rollup-plugin-vue.common.js:82:20)
    at processScript (vue-plugin/node_modules/rollup-plugin-vue/dist/rollup-plugin-vue.common.js:168:18)
    at vueTransform (vue-plugin/node_modules/rollup-plugin-vue/dist/rollup-plugin-vue.common.js:206:14)
```

If I comment that line out, everything gets compiled fine. I tried to mess with configuration a little bit, but to no avail.

**Comment by znck** [comment]
Will look into it, next week. 

🗺 Travelling.

**Comment by znck** [comment]
Update [rollup-plugin-vue](http://github.com/znck/rollup-plugin-vue) to latest version (2.2.13).

**Comment by sunyatasattva** [comment]
Gonna try that ASAP. Thank you for looking into it :)
